In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn

In [7]:
data = pd.read_csv("D:\CODE\jupyter notebook\data\(日月光华)PyTorch深度学习教程课件\(日月光华)PyTorch深度学习教程课件\daatset\credit-a.csv", header=None)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 653 entries, 0 to 652
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       653 non-null    int64  
 1   1       653 non-null    float64
 2   2       653 non-null    float64
 3   3       653 non-null    int64  
 4   4       653 non-null    int64  
 5   5       653 non-null    int64  
 6   6       653 non-null    int64  
 7   7       653 non-null    float64
 8   8       653 non-null    int64  
 9   9       653 non-null    int64  
 10  10      653 non-null    int64  
 11  11      653 non-null    int64  
 12  12      653 non-null    int64  
 13  13      653 non-null    int64  
 14  14      653 non-null    float64
 15  15      653 non-null    int64  
dtypes: float64(4), int64(12)
memory usage: 81.8 KB


In [11]:
X = data.iloc[:, :-1]
Y = data.iloc[:, -1].replace(-1, 0)
X = torch.from_numpy(X.values).type(torch.float32)
Y = torch.from_numpy(Y.values).type(torch.float32).reshape(-1, 1)
Y.shape

torch.Size([653, 1])

In [13]:
model = nn.Sequential(
    nn.Linear(15, 1),
    nn.Sigmoid()
)
loss_fn = nn.BCELoss()
opt = torch.optim.Adam(model.parameters(), lr=0.0001)
batch_size = 16
num_batch = X.size(0)//batch_size
epoches = 5000

In [15]:
for epoch in range(epoches):
    for i in range(num_batch):
        start = i * batch_size
        end = start + batch_size
        x = X[start: end]
        y = Y[start: end]
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        opt.zero_grad()
        loss.backward()
        opt.step()

tensor(0.0669, grad_fn=<BinaryCrossEntropyBackward0>)
<bound method Module.named_parameters of Sequential(
  (0): Linear(in_features=15, out_features=1, bias=True)
  (1): Sigmoid()
)>


In [19]:
print(loss)
print(list(model.named_parameters()))

tensor(0.0669, grad_fn=<BinaryCrossEntropyBackward0>)
[('0.weight', Parameter containing:
tensor([[-1.7109e-01, -9.5503e-03,  8.5700e-03,  2.5711e-01,  1.3916e-01,
         -1.2736e-02,  1.6760e-01, -1.2903e-01,  3.4149e+00,  3.0618e-01,
         -1.5307e-01, -3.1793e-01, -7.6856e-02,  8.4107e-04, -3.4074e-04]],
       requires_grad=True)), ('0.bias', Parameter containing:
tensor([-0.2599], requires_grad=True))]


In [20]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-1.7109e-01, -9.5503e-03,  8.5700e-03,  2.5711e-01,  1.3916e-01,
                       -1.2736e-02,  1.6760e-01, -1.2903e-01,  3.4149e+00,  3.0618e-01,
                       -1.5307e-01, -3.1793e-01, -7.6856e-02,  8.4107e-04, -3.4074e-04]])),
             ('0.bias', tensor([-0.2599]))])