In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn

D:\Anaconda\envs\wyc_gpu\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\Anaconda\envs\wyc_gpu\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
D:\Anaconda\envs\wyc_gpu\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
t = torch.FloatTensor([1, 2, 3])
t.dtype

torch.float32

In [4]:
array = np.arange(12).reshape(3, 4)
array.dtype

dtype('int32')

In [5]:
torch.from_numpy(array).dtype

torch.int32

In [6]:
# 0到1随机分布的数据
torch.rand(2, 3)

tensor([[0.5806, 0.2099, 0.1634],
        [0.3693, 0.3250, 0.8557]])

In [7]:
# 标准正态分布的随机数
torch.randn(2, 3)

tensor([[-0.2840,  0.5858,  1.3702],
        [ 0.0042, -2.0472, -0.0600]])

In [8]:
# 全0的数
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# 全1的数
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
# like
torch.ones_like(t)

tensor([1., 1., 1.])

In [11]:
# 将张量在GPU开辟空间，放到GPU上
t = torch.rand(2,3)
print(t.size(0))
print(t.device)
print(t)
if torch.cuda.is_available():
    t = t.to('cuda')
t.device

2
cpu
tensor([[0.2051, 0.9883, 0.2558],
        [0.1427, 0.6379, 0.3743]])


device(type='cuda', index=0)

In [12]:
# 转换类型
t.type(torch.int16)

tensor([[0, 0, 0],
        [0, 0, 0]], device='cuda:0', dtype=torch.int16)

In [13]:
# 转换类型（快捷方式）
t.long()
t.float()

tensor([[0.2051, 0.9883, 0.2558],
        [0.1427, 0.6379, 0.3743]], device='cuda:0')

In [14]:
# 广播原则
print(t)
t = t + 3
print(t)

tensor([[0.2051, 0.9883, 0.2558],
        [0.1427, 0.6379, 0.3743]], device='cuda:0')
tensor([[3.2051, 3.9883, 3.2558],
        [3.1427, 3.6379, 3.3743]], device='cuda:0')


In [15]:
t = torch.randn(2, 3)
# 求绝对值：abs
torch.abs(t)
# 求均值： mean
torch.mean(t)
# 矩阵乘法：matmul
# 转置：T
t.matmul(t.T)

tensor([[ 3.6489, -2.5820],
        [-2.5820,  2.5034]])

In [19]:
t = torch.randn(3,8)
print(t)
t.view(-1, 2)

tensor([[-0.2035,  0.5076, -1.0700,  0.7374, -1.8471, -0.5425, -1.0636,  1.4705],
        [ 1.5083,  0.4609,  0.2979,  0.0552,  0.0042, -0.0081,  1.9388,  0.3156],
        [ 0.2222,  1.9283, -0.4621,  0.5001, -0.0286, -0.1460, -0.2228, -1.2877]])


tensor([[-0.2035,  0.5076],
        [-1.0700,  0.7374],
        [-1.8471, -0.5425],
        [-1.0636,  1.4705],
        [ 1.5083,  0.4609],
        [ 0.2979,  0.0552],
        [ 0.0042, -0.0081],
        [ 1.9388,  0.3156],
        [ 0.2222,  1.9283],
        [-0.4621,  0.5001],
        [-0.0286, -0.1460],
        [-0.2228, -1.2877]])

In [20]:
t = torch.randn(12, 3, 19, 19)
t.view(12, -1)

tensor([[-1.0040, -0.9768,  0.9697,  ...,  1.1848,  1.2104, -1.6980],
        [-0.0065,  0.3427, -0.7105,  ...,  1.0642,  0.3624, -1.0172],
        [ 0.5927, -0.1148,  0.8907,  ...,  1.3223,  1.4606, -1.1313],
        ...,
        [-1.9458, -2.1196,  0.1240,  ...,  1.9749,  0.6566,  0.5997],
        [-2.7971,  0.3799,  1.7193,  ...,  0.9823,  1.6000, -0.6389],
        [ 0.3340,  0.1246, -0.7388,  ...,  0.7414,  0.7832, -1.0897]])

In [32]:
t = torch.randn(1,12,19,19)
print(t.shape)
t = t.squeeze()
print(t.shape)

torch.Size([1, 12, 19, 19])
torch.Size([12, 19, 19])


In [41]:
# 自动微分（grad）
t = torch.randn(3, 4, requires_grad=True)
t.requires_grad
y = t + 5
z = y * 2
final = z.mean()
print(t)
print(y)
print(y.grad_fn)
print(z)
print(z.grad_fn)
print(final)
print(final.grad_fn)
final.backward()
# 求t的梯度， d(final)/d(t)
t.grad

tensor([[-1.4213, -0.0466,  1.1939,  2.0524],
        [ 0.7011,  0.4126, -1.1774, -0.3041],
        [ 0.8673, -0.0593,  0.1382, -0.6432]], requires_grad=True)
tensor([[3.5787, 4.9534, 6.1939, 7.0524],
        [5.7011, 5.4126, 3.8226, 4.6959],
        [5.8673, 4.9407, 5.1382, 4.3568]], grad_fn=<AddBackward0>)
tensor([[ 7.1573,  9.9069, 12.3878, 14.1047],
        [11.4021, 10.8251,  7.6452,  9.3919],
        [11.7346,  9.8814, 10.2764,  8.7135]], grad_fn=<MulBackward0>)
tensor(10.2856, grad_fn=<MeanBackward0>)


tensor([[0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667]])

In [42]:
# 不跟踪梯度：
with torch.no_grad():
    y = t + 2
    print(y.requires_grad)

False


In [44]:
# 不跟踪梯度：
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2 + 2 * x + 1
y_detached = y.detach()
print("y:", y) 
print("y_detached:", y_detached) 

y: tensor(16., grad_fn=<AddBackward0>)
y_detached: tensor(16.)
